import 'package:flutter/cupertino.dart';

class AppColor {
  static const Color primaryColor = Color(0xffFF006B);
  static const Color primaryBackgroundColor =
  Color.fromARGB(255, 251, 251, 251);
  static const Color loginButtonColor = Color(0xffFF006B);
  static const Color fontColor = Color(0xff1F1F39);
  static const Color dividerColor = Color(0xffEFF0F6);
  static const Color textSignupColor = Color(0xff6E7191);
  static const Color addNewBtnColor = Color(0xffFFEDF4);
  static const Color myAddrBgColor = Color(0xffF7F7FC);
  static const Color homeIconColor = Color(0xff008BBA);
  static const Color activeTxtColor = Color(0xff008BBA);
  static const Color activeTxtBorderColor = Color(0xff6FF8A6);
  static const Color deleveryColor = Color(0xffBDEFFF);
  static const Color deleteBtnColor = Color(0xffE93C3C);
  static const Color searchBarbg = Color(0xffF7F7FC);
  static const Color viewAllbg = Color(0xffFFEDF4);
  static const Color itembg = Color(0xffEFF0F6);
  static const Color delivaryActive = Color(0xff008BBA);
  static const Color delivaryInactive = Color(0xffBDEFFF);
  static const Color green = Color(0xff1AB759);
  static const Color yellow = Color(0xffFFDB1F);
  static const Color gray = Color(0xff6E7191);
  static const Color bgColor = Color(0xffF7F7FC);
  static const Color darkGray = Color(0xff1F1F39);
}

class Images {
  static String get change_language => 'assets/icons/change_language.svg';
  static String get terms_condition => 'assets/icons/terms_condition.svg';
  static String get tomato => 'assets/icons/tomato.svg';
  static String get privacy => 'assets/icons/privacy.svg';
  static String get calling => 'assets/icons/calling.svg';
  static String get about_us => 'assets/icons/about_us.svg';
  static String get homee => 'assets/icons/home.svg';
  static String get home => 'assets/images/home.png';
  static String get menu => 'assets/images/menu.png';
  static String get offer => 'assets/images/offer.png';
  static String get cartg => 'assets/images/cart.png';
  static String get profile_circle => 'assets/images/profile_circle.png';
  static String get back => 'assets/icons/back.svg';
  static String get profile_2 => 'assets/images/profile_2.png';
  static String get profile => 'assets/images/profile.png';
  static String get order => 'assets/icons/order.svg';
  static String get chat => 'assets/icons/chat.svg';
  static String get other => 'assets/icons/other.svg';
  static String get work => 'assets/icons/work.svg';
  static String get address => 'assets/icons/address.svg';
  static String get change_pass => 'assets/icons/change_pass.svg';
  static String get contact => 'assets/images/contact.png';
  static String get logout => 'assets/icons/logout.svg';
  static String get edit_image => 'assets/images/edit_image.png';
  static String get edit_address => 'assets/icons/edit_address.svg';
  static String get location => 'assets/images/location.png';
  static String get tick => 'assets/icons/tick-circle.svg';
  static String get flagEn => 'assets/images/en.png';
  static String get flagDe => 'assets/images/de.png';
  static String get flagBd => 'assets/images/bd.png';
  static String get flagAr => 'assets/images/ar.png';
  static String get flagFr => 'assets/images/fr.png';
  static String get iconHome => 'assets/icons/home.svg';
  static String get iconMenu => 'assets/icons/menu.svg';
  static String get iconOffers => 'assets/icons/offers.svg';
  static String get iconProfile => 'assets/icons/profile-circle.svg';
  static String get iconArrowDown => 'assets/icons/arrow_down.svg';
  static String get demo => 'assets/images/demo.jpeg';
  static String get offer1 => 'assets/images/offer1.png';
  static String get offer2 => 'assets/images/offer2.png';
  static String get item1 => 'assets/images/item1.png';
  static String get cat1 => 'assets/images/cat1.png';
  static String get cat2 => 'assets/images/cat2.png';
  static String get iconCart => 'assets/icons/bag.svg';
  static String get iconDetails => 'assets/icons/detailsIcon.svg';
  static String get shop => 'assets/icons/shop.svg';
  static String get person => 'assets/icons/person.svg';
  static String get gallery => 'assets/icons/gallery.svg';
  static String get right_arrow => 'assets/icons/right_arrow.svg';
  static String get dot_icon => 'assets/icons/dot_icon.svg';
  static String get send => 'assets/icons/send.svg';
  static String get iconRowVertical => 'assets/icons/row-vertical.svg';
  static String get iconListView => 'assets/icons/list_icon.svg';
  static String get iconGridView => 'assets/icons/grid_icon.svg';
  static String get iconSearch => 'assets/icons/icon_search.svg';
  static String get nonVeg => 'assets/images/non_veg.png';
  static String get IconClose => 'assets/icons/close-circle.svg';
  static String get active_order => 'assets/icons/active_order.svg';
  static String get deactive => 'assets/icons/deactive.svg';
  static String get IconAddItem => 'assets/icons/add-circle.svg';
  static String get IconRemoveItem => 'assets/icons/minus-circle.svg';
  static String get veg => 'assets/images/veg.png';
  static String get offer3 => 'assets/images/offer3.png';
  static String get offer4 => 'assets/images/offer4.png';
  static String get IconVariation => 'assets/icons/circle.svg';
  static String get IconVariationSelected => 'assets/icons/selected_circle.svg';
  static String get iconTickedNo => 'assets/icons/ticked-no-square.svg';
  static String get iconTickedYes => 'assets/icons/ticked-yes-square.svg';
  static String get message => 'assets/icons/messages.svg';
  static String get call => 'assets/icons/call.svg';
  static String get addOns1 => 'assets/images/addons1.png';
  static String get addOns2 => 'assets/images/pepsi.png';
  static String get mapView => 'assets/images/map.png';
  static String get mapViewLarge => 'assets/images/mapLarge.png';
  static String get homeIcon => 'assets/icons/home_icon.svg';
  static String get locationIcon => 'assets/icons/location_icon.svg';
  static String get officeIcon => 'assets/icons/office_icon.svg';
  static String get sms_tracking => 'assets/icons/sms-tracking.svg';
  static String get cll_center => 'assets/icons/call-center.svg';
  static String get thik => 'assets/icons/thik.svg';
  static String get iconCard => 'assets/icons/card.svg';
  static String get iconCod => 'assets/icons/cod.svg';
  static String get iconPromo => 'assets/icons/promo_icon.svg';
  static String get iconArrowRight => 'assets/icons/arrow-right.svg';
  static String get iconRouting => 'assets/icons/routing_icon.svg';
  static String get iconTimeline => 'assets/icons/timeline.svg';
  static String get iconTrash => 'assets/icons/trash.svg';
  static String get iconEditProfile => 'assets/icons/edit_profile.svg';
}

class ScreenSize {
  BuildContext context;
  ScreenSize(this.context);
  double get mainHeight => MediaQuery.of(context).size.height;
  double get mainWidth => MediaQuery.of(context).size.width;
}
